name: Releases

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: echo VERSION=$(cat Assets/CostCenter/package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]') >> $GITHUB_ENV

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: v${{ env.VERSION }}
          token: ${{ secrets.GIT_TOKEN }}
      
      - name: Update Release Notes
        id: prepare_release_notes
        shell: bash
        run: |
          export CHANGELOG=$(awk 's{ print ""; print}; $0~v {print; s=0; next}; s=0' RS= v=${{ env.VERSION }} ${{ github.workspace }}/CHANGELOG.md)
          echo "$CHANGELOG" >> release_notes.md

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Cost Center SDK v${{ env.VERSION }}
          body_path: release_notes.md
          draft: false
          prerelease: false
